modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL-3.0"
issueTrackerURL="https://github.com/zach2039/oldguns/issues" #optional
[[mods]] #mandatory
modId="oldguns" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Old Guns Mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/old-guns-mod" #optional
logoFile="oldguns.png" #optional
credits="Friends who helped test" #optional
authors="Zach2039" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Antique weapons for that colonial feel.
'''
[[dependencies.oldguns]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.oldguns]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.18.1-61,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oldguns]]
    modId="jei"
    mandatory=false
    versionRange="[1.18.1-9.1.0.41,)"
    ordering="NONE"
    side="BOTH"