modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="AGPL-3.0"
issueTrackerURL="https://github.com/zach2039/oldguns/issues" #optional
[[mods]] #mandatory
modId="oldguns" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Old Guns Mod" #mandatory
updateJSONURL="https://www.zach2039.com/mods/oldguns/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/old-guns-mod" #optional
logoFile="oldguns.png" #optional
credits="Contributors, artists, and those who helped test!" #optional
authors="Zach2039" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Antique weapons for that colonial feel.
'''
[[dependencies.oldguns]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.0.94,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.oldguns]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19-,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.oldguns]]
    modId="jei"
    mandatory=false
    versionRange="[1.19-,)"
    ordering="NONE"
    side="CLIENT"
